CREATE TABLE IF NOT EXISTS content_moderation_evidence (
  id VARCHAR(191) PRIMARY KEY,
  request_id VARCHAR(191) NOT NULL,
  user_id VARCHAR(191) NULL,
  api_key_id VARCHAR(191) NULL,
  provider_id VARCHAR(191) NULL,
  upstream_service_id VARCHAR(191) NULL,
  upstream_account_id VARCHAR(191) NULL,
  moderation_model VARCHAR(255) NOT NULL,
  input_sha256 VARCHAR(128) NOT NULL,
  input_text LONGTEXT NULL,
  categories JSON NOT NULL,
  category_scores JSON NOT NULL,
  flagged BOOLEAN NOT NULL DEFAULT FALSE,
  created_at_unix_secs BIGINT UNSIGNED NOT NULL,
  expires_at_unix_secs BIGINT UNSIGNED NOT NULL,
  redacted_at_unix_secs BIGINT UNSIGNED NULL,
  INDEX idx_content_moderation_evidence_request (request_id),
  INDEX idx_content_moderation_evidence_expiry (expires_at_unix_secs, id),
  INDEX idx_content_moderation_evidence_actor (user_id, api_key_id, created_at_unix_secs)
);
